[package]
name = "ferrite-core"
description = "Validated virtual tree and HTML rendering primitives for Ferrite."
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
