[package]
name = "ferrite-dev-server"
description = "Development and production HTTP adapters for Ferrite applications."
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ferrite-builder = { path = "../ferrite-builder", version = "=0.1.0" }
ferrite-client-bundler = { path = "../ferrite-client-bundler", version = "=0.1.0" }
ferrite-core = { path = "../ferrite-core", version = "=0.1.0" }
ferrite-page-renderer = { path = "../ferrite-page-renderer", version = "=0.1.0" }
ferrite-protocol = { path = "../ferrite-protocol", version = "=0.1.0" }
ferrite-router = { path = "../ferrite-router", version = "=0.1.0" }
flate2 = { workspace = true }
getrandom = { workspace = true }
httparse = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
