import Image from "next/image";

const repositoryUrl = "https://github.com/integrate-your-mind/ferrite";
const demoSha = "8716f30c83b9e4fc0835c2f37f9c00bd26e8152d";
const baseSha = "8539f4a9288321f002658cebf6ac25a9bd952519";
const features = [
  ["Available", "Compiler-owned module graph", "Runtime edges, cycle diagnostics, and invalidation are owned by the Rust build contract."],
  ["Available", "Rust SSR and routing", "Filesystem routes, layouts, metadata, escaping, and artifact-backed serving."],
  ["Available", "TypeScript developer surface", "TSX, browser bundles, client islands, hydration, hooks, navigation, and boundaries."],
  ["Partial", "Server actions", "CSRF, replay, proxy, audit, and public-error controls exist; session-bound auth is incomplete."],
  ["Experimental", "Production-shaped deployment", "Versioned artifacts, integrity checks, nginx, Docker, and systemd templates."],
  ["Planned", "Public distribution", "Registry packages, public CLI acquisition, hosted CI, and broad clean-machine onboarding."],
] as const;
const technologies = ["Rust 2024", "TypeScript", "JavaScript", "Node.js", "esbuild", "WebAssembly", "Node-API", "nginx", "Docker", "systemd", "Playwright", "happy-dom"];
const links = [
  ["Source repository", repositoryUrl],
  ["LICENSE", repositoryUrl + "/blob/main/LICENSE"],
  ["Contributing", repositoryUrl + "/blob/main/CONTRIBUTING.md"],
  ["Security policy", repositoryUrl + "/blob/main/SECURITY.md"],
  ["Code of conduct", repositoryUrl + "/blob/main/CODE_OF_CONDUCT.md"],
  ["Architecture at demo head", repositoryUrl + "/blob/" + demoSha + "/docs/architecture.md"],
  ["Deployment guide at demo head", repositoryUrl + "/blob/" + demoSha + "/docs/deployment.md"],
  ["PR #4 proof receipt", repositoryUrl + "/blob/" + baseSha + "/docs/proof-receipts/2026-07-18T141937Z-f7a1b1f-pr4-checkpoint.md"],
  ["Draft PR #4", repositoryUrl + "/pull/4"],
  ["Draft demo PR #5", repositoryUrl + "/pull/5"],
];
function Status({ value }: { value: string }) { return <span className={"status status-" + value.toLowerCase()}>{value}</span>; }
function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href}>{children}<span aria-hidden="true">↗</span></a>; }

export default function Home() {
  return <main id="top">
    <a className="skip-link" href="#content">Skip to content</a>
    <header className="site-header">
      <a className="brand" href="#top" aria-label="Ferrite home"><Image src="/ferrite-mark.svg" alt="" width={24} height={24} priority /><span>Ferrite</span></a>
      <nav aria-label="Primary navigation"><a href="#demo">Demo</a><a href="/blog">Blog</a><a href="#features">Capabilities</a><a href="#architecture">Architecture</a><a href="#setup">Setup</a><a href="#status">Status</a></nav>
      <ExternalLink href={repositoryUrl}>Source </ExternalLink>
    </header>
    <section className="hero" aria-labelledby="hero-title">
      <Image className="hero-image" src="/demos/docs-home-desktop.png" alt="Ferrite Docs Workbench home route rendered from an artifact-backed local serve" fill sizes="100vw" priority unoptimized />
      <div className="hero-scrim" aria-hidden="true" />
      <div className="hero-copy"><p className="eyebrow"><span className="signal-dot" /> Open source · source-build preview</p><h1 id="hero-title">Ferrite</h1><p className="hero-statement">Rust owns the control plane. <strong>TypeScript stays on top.</strong></p><p className="hero-summary">A Rust-first framework experiment for React-like UI and Next.js-like applications, with explicit builds, route graphs, rendering, and artifact-backed serving.</p><div className="hero-actions"><a className="button primary" href="#demo">Explore the real demo</a><a className="button" href="/blog/tic-tac-toe">Read the Ferrite Tic Tac Toe demo</a><a className="button" href="/blog/tic-tac-toe-3d">Read the 3-D Three.js demo</a><ExternalLink href={repositoryUrl}>Read the source </ExternalLink></div><p className="hero-note">Open-source developer preview. Not a managed public-production release.</p><p className="hero-receipt"><code>examples/docs-workbench</code><span>pinned demo-branch artifact serve · {demoSha.slice(0, 7)}</span></p></div>
    </section>
	    <section className="proof-strip" aria-label="Verified local proof"><div><strong>509</strong><span>tests at the reviewed PR #4 checkpoint</span></div><div><strong>10</strong><span>Chrome scenarios at that checkpoint</span></div><div><strong>Captured</strong><span>Rust dev-server coverage report</span></div><p>Pinned demo head <code>{demoSha.slice(0, 7)}</code> · local evidence, not current-head hosted deployment proof.</p></section>
    <div id="content" tabIndex={-1}>
      <section className="section intro-grid" aria-labelledby="problem-title"><div className="kicker">01 / Why Ferrite</div><div><h2 id="problem-title">Make the build and runtime contract visible.</h2><p className="lede">Modern app tooling can make source discovery, route behavior, rendering, bundling, and deployment feel like separate systems. Ferrite explores one explicit path from TSX source to a verified artifact.</p><div className="three-up"><div><b>Control</b><p>One compiler-owned graph carries source ownership through build and serve.</p></div><div><b>Fast failure</b><p>Cycles, stale artifacts, path escapes, and ambiguous requests fail at a named boundary.</p></div><div><b>Honest proof</b><p>Local runtime evidence is labeled separately from hosted CI, registry, and production claims.</p></div></div></div></section>
      <section className="section demo-section" id="demo" aria-labelledby="demo-title"><div className="section-lead"><div className="kicker">02 / Real demo</div><h2 id="demo-title">A docs app, rendered for real.</h2><p className="lede">These captures come from the source-built Docs Workbench example at the exact demo head. No fake browser chrome or invented output.</p><div className="route-chips"><code>/</code><code>/guides/architecture</code><code>/reference/router</code><code>/guides/unlisted/path</code></div></div><div className="demo-gallery"><figure className="capture capture-wide"><Image src="/demos/docs-guide-desktop.png" alt="Docs Workbench architecture guide rendered from a generated guide route" width={1280} height={900} unoptimized /><figcaption><b>Generated guide route</b><span>/guides/architecture · desktop</span></figcaption></figure><figure className="capture"><Image src="/demos/docs-catchall-desktop.png" alt="Docs Workbench unlisted catch-all route with an explicit unavailable-content state" width={1280} height={900} unoptimized /><figcaption><b>Odd catch-all path</b><span>/guides/unlisted/path · application-level unavailable state</span></figcaption></figure><figure className="capture capture-mobile"><Image src="/demos/docs-mobile-nav.png" alt="Docs Workbench responsive mobile navigation open at 390 pixels wide" width={390} height={844} unoptimized /><figcaption><b>Hydrated island</b><span>390 × 844 · menu open</span></figcaption></figure></div><p className="media-note">All screenshots: exact local artifact-backed serve at <code>{demoSha}</code>, captured 2026-07-18. A live Ferrite demo URL is not available.</p></section>
      <section className="section code-section" aria-labelledby="code-title"><div className="kicker">03 / Code to output</div><div className="code-grid"><div><h2 id="code-title">The authoring surface stays readable.</h2><p className="lede">Start with ordinary TypeScript and TSX. Ferrite’s compiler and Rust server own the graph, artifact, and request boundaries underneath.</p></div><div className="code-panel"><span className="code-label">Abridged verified route logic · examples/docs-workbench/app/guides/[...slug]/page.tsx</span><pre><code>{"export function generateStaticParams() {\n  return [{ slug: [\"getting-started\"] },\n          { slug: [\"architecture\"] }];\n}\n\nconst key = params.slug.join(\"-\");\nconst guide = guides[key] ?? {\n  title: params.slug.join(\" / \"),\n  kicker: \"Unlisted guide path\",\n};"}</code></pre><div className="code-output"><span>OUTPUT</span><b>/guides/architecture</b><small>SSR HTML → generated metadata → isolated navigation island</small></div></div></div></section>
      <section className="section capabilities" id="features" aria-labelledby="features-title"><div className="kicker">04 / Capability matrix</div><div className="section-heading"><h2 id="features-title">A foundation, labeled by proof.</h2><p className="lede">Status is deliberately narrower than ambition. Partial, experimental, and planned work is not presented as complete.</p></div><div className="capability-table">{features.map(([status, title, copy]) => <article key={title}><Status value={status} /><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
      <section className="section architecture" id="architecture" aria-labelledby="architecture-title"><div className="kicker">05 / Architecture</div><div className="architecture-layout"><div><h2 id="architecture-title">Source → graph → artifact → serve.</h2><p className="lede">The Rust control plane validates ownership and integrity before binding a port. JavaScript and TypeScript remain the expressive layer for routes, layouts, and browser islands.</p><dl className="facts"><div><dt>State</dt><dd>Filesystem source and generated artifacts</dd></div><div><dt>Services</dt><dd>No model or database required</dd></div><div><dt>Optional edge</dt><dd>nginx, Docker, or systemd</dd></div></dl></div><ol className="flow" aria-label="Ferrite request and build flow"><li><b>01</b><span>TSX source</span><small>routes · layouts · islands</small></li><li><b>02</b><span>Node compiler</span><small>TSX execution · bundles</small></li><li><b>03</b><span>Rust graph</span><small>edges · SSR · protocol</small></li><li><b>04</b><span>Verified artifact</span><small>manifest · hashes · assets</small></li><li><b>05</b><span>Ferrite serve</span><small>budgets · logs · browser</small></li></ol></div><aside className="security-callout"><b>Security boundary</b><p>When explicitly configured, form actions support CSRF-token, replay-window, trusted-proxy, audit-log, and public-error controls. Session-bound authentication, distributed replay, stable inferred action IDs, and external tracing remain incomplete.</p></aside></section>
      <section className="section setup" id="setup" aria-labelledby="setup-title"><div className="kicker">06 / Source setup</div><div className="section-heading"><h2 id="setup-title">Try the source-built path.</h2><p className="lede">Rust 1.95, Node.js 22+, pnpm 11.7, and a supported browser are required for the full proof suite. Ferrite crates separately declare Rust 1.85 as their minimum supported compiler.</p></div><div className="commands"><div><h3>Install and build</h3><pre><code>{"git clone " + repositoryUrl + ".git\ncd ferrite\npnpm install --frozen-lockfile\ncargo build --workspace\npnpm build"}</code></pre></div><div><h3>Verify</h3><pre><code>{"pnpm typecheck\npnpm lint\npnpm test"}</code></pre></div><div><h3>Serve an artifact</h3><pre><code>{"pnpm build:example\ntarget/debug/ferrite serve \\\n  --project examples/basic \\\n  --artifact .ferrite/build \\\n  --page-renderer packages/runtime/bin/render-artifact.mjs \\\n  --once --request-path /posts/abc"}</code></pre></div></div><p className="env-note">Environment names only: <code>FERRITE_ACTION_CSRF</code> <code>FERRITE_PUBLIC_ORIGIN</code>. Values are intentionally omitted.</p></section>
      <section className="section status-section" id="status" aria-labelledby="status-title"><div className="status-top"><div className="kicker">07 / Status & limits</div><Status value="Partial" /></div><h2 id="status-title">Public source-build developer preview. Candidate delivery unit.</h2><div className="status-grid"><div><h3>Works now</h3><ul><li>Rust SSR, filesystem routes, and artifact-only serving</li><li>Deterministic graph, invalidation, and reproducible output</li><li>TSX, islands, hydration, navigation, and forms</li><li>Local lint, typecheck, build, tests, coverage, and package proof</li></ul></div><div><h3>Not proven</h3><ul><li>Hosted Actions (startup failure before job allocation)</li><li>Public CLI, registry packages, or live demo</li><li>Current integrated-head nginx proxy execution</li><li>Native Windows runtime and production capacity</li></ul></div><div><h3>Next gates</h3><ul><li>Registry publication and public CLI acquisition</li><li>Hosted CI and exact-source proxy proof</li><li>Cross-platform clean-machine onboarding</li><li>Staging, rollback, capacity, observability</li></ul></div></div></section>
      <section className="section technology" aria-labelledby="technology-title"><div><div className="kicker">08 / Stack & links</div><h2 id="technology-title">Small stack. Clear edges.</h2><p className="lede">No managed model or database is required by the current framework experiment. Source and docs are open to review and contribution; hosted deployment proof is still a workstream.</p></div><div><ul className="technology-list">{technologies.map((tech) => <li key={tech}>{tech}</li>)}</ul><div className="link-list">{links.map(([label, href]) => <ExternalLink key={label} href={href}>{label} </ExternalLink>)}</div></div></section>
    </div>
    <footer><a className="brand" href="#top"><Image src="/ferrite-mark.svg" alt="" width={20} height={20} /><span>Ferrite</span></a><p>Source-backed preview · demo head {demoSha.slice(0, 7)} · no production-readiness claim.</p><a href="#top">Back to top ↑</a></footer>
  </main>;
}
