import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const file = (name) => new URL(`../${name}`, import.meta.url);
const source = (name) => readFile(file(name), "utf8");

test("uses Ferrite app-directory contracts and shared document", async () => {
  const [layout, document, chrome, examples, packageJson, lockfile, metadata, limitations, compare] = await Promise.all([source("app/layout.tsx"), source("app/document.tsx"), source("app/components/SiteChrome.tsx"), source("app/examples/ExamplesIsland.tsx"), source("package.json"), source("pnpm-lock.yaml"), source("app/metadata.ts"), source("app/docs/limitations/page.tsx"), source("app/compare/migration-matrix/page.tsx")]);
  assert.match(layout, /@ferrite\/runtime/); assert.match(document, /data-ferrite-document/); assert.match(document, /siteStyles/);
  assert.match(layout, /openGraph/); assert.match(layout, /twitter/); assert.match(metadata, /FERRITE_SITE_ORIGIN/); assert.match(metadata, /siteUrl/);
  assert.match(chrome, /noscript/); assert.match(chrome, /mobile-nav-fallback/);
  assert.match(document, /focus-visible/); assert.match(limitations, /<caption>/); assert.match(compare, /<caption>/);
  assert.match(examples, /"use client"/); assert.match(examples, /fetch\(path\)/); assert.match(examples, /request\("\/demo-data\.json"\)/); assert.match(examples, /request\("\/demo-data-missing\.json"\)/);
  assert.doesNotMatch(packageJson, /next|vinext|react-dom/); assert.match(packageJson, /ferrite-cli/); assert.match(packageJson, /pnpm@11\.7\.0/); assert.match(packageJson, /@ferrite\/runtime/); assert.match(packageJson, /eslint/); assert.match(packageJson, /typescript/); assert.match(lockfile, /link:\.\.\/packages\/runtime/);
});

test("route inventory and comparison series remain source-backed", async () => {
  for (const route of ["app/page.tsx", "app/docs/page.tsx", "app/docs/getting-started/page.tsx", "app/docs/architecture/page.tsx", "app/docs/limitations/page.tsx", "app/docs/deployment/page.tsx", "app/examples/page.tsx", "app/blog/page.tsx", "app/blog/tic-tac-toe/page.tsx", "app/blog/tic-tac-toe-3d/page.tsx", "app/compare/page.tsx", "app/compare/state-events/page.tsx", "app/compare/rendering-lifecycle/page.tsx", "app/compare/routing-data-build/page.tsx", "app/compare/migration-matrix/page.tsx", "app/compare/incompatibilities/page.tsx", "app/compare/codemod-boundary/page.tsx", "app/compare/when-to-stay/page.tsx"]) await access(file(route));
  const [home, architecture, deployment, readme] = await Promise.all([source("app/page.tsx"), source("app/docs/architecture/page.tsx"), source("app/docs/deployment/page.tsx"), source("README.md")]);
  assert.match(home, /8716f30/); assert.match(home, /local evidence/i); assert.match(home, /No drop-in React claim/i);
  for (const renderingMode of [/server-side rendering/i, /client-side rendering/i, /static site generation/i]) assert.match(home, renderingMode);
  for (const renderingMode of [/request-time server rendering/i, /browser mounting and hydration/i, /prerendered static delivery/i]) assert.match(architecture, renderingMode);
  assert.match(deployment, /does not execute Ferrite's native listener or request-time renderer inside a Worker/i);
  assert.match(readme, /dedicated fetch-based adapter/i);
  for (const content of [home, architecture, deployment, readme]) assert.doesNotMatch(content, /plain Worker adapter/i);
});

test("deployment adapter preserves hosting identity and hardens responses", async () => {
  const adapter = await source("deploy-adapter.mjs"); const hosting = JSON.parse(await source(".openai/hosting.json"));
  assert.equal(hosting.project_id, "appgprj_6a5b984c7d4481919ec1cf6bbcbd55c8");
  for (const required of ["sourceBuildId", "staging", "rollback", "size mismatch", "SHA-256 mismatch", "symlink/reparse", "404", "Cache-Control", "X-Content-Type-Options", "Content-Security-Policy", "GENERATED_SERVER_ENTRY", "FERRITE_SITES_SERVE"]) assert.match(adapter, new RegExp(required.replace(/[/.]/g, "\\$&")));
  assert.match(adapter, /join\(dist, "server", "index\.js"\)/);
  assert.match(adapter, /prerendered/); assert.match(adapter, /manifest\.files/); assert.match(adapter, /FERRITE_SITE_ORIGIN/); assert.match(adapter, /renderSitemap/); assert.match(adapter, /renderRobots/); assert.doesNotMatch(adapter, /home-page fallback|routes\.has\("\/"\)/i);
});

test("robots and sitemap are adapter-generated templates", async () => {
  const sitemap = await source("public/sitemap.xml"); const robots = await source("public/robots.txt");
  assert.match(robots, /generated by deploy-adapter\.mjs/i); assert.doesNotMatch(robots, /https:\/\/ferrite\.dev/);
  assert.match(sitemap, /validated Ferrite route manifest/i); assert.doesNotMatch(sitemap, /https:\/\/ferrite\.dev/);
  await access(file("public/robots.txt")); await access(file("public/sitemap.xml")); await access(file("public/ferrite-mark.svg")); await access(file("public/og.png"));
  const manifest = JSON.parse(await source("public/demos/capture-manifest.json")); assert.equal(manifest.source.commit, "8716f30c83b9e4fc0835c2f37f9c00bd26e8152d");
});
