[package]
name = "ferrite-node"
description = "Node-API bindings for Ferrite's Rust server renderer."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ferrite-ssr = { path = "../ferrite-ssr", version = "0.1.0" }
