use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug)]
pub enum RouterError {
    AppDirMissing(PathBuf),
    Io(std::io::Error),
    InvalidRouteSegment(String),
}

impl fmt::Display for RouterError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RouterError::AppDirMissing(path) => {
                write!(f, "app directory does not exist: {}", path.display())
            }
            RouterError::Io(error) => write!(f, "{error}"),
            RouterError::InvalidRouteSegment(segment) => {
                write!(f, "invalid route segment `{segment}`")
            }
        }
    }
}

impl std::error::Error for RouterError {}

impl From<std::io::Error> for RouterError {
    fn from(error: std::io::Error) -> Self {
        RouterError::Io(error)
    }
}

pub type Result<T> = std::result::Result<T, RouterError>;

pub const GENERATED_ROUTE_TYPES_HEADER: &str = "/* auto-generated by ferrite */";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteParamKind {
    Dynamic,
    CatchAll,
    OptionalCatchAll,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RouteParam {
    pub name: String,
    pub kind: RouteParamKind,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Route {
    pub path: String,
    pub file: PathBuf,
    pub layouts: Vec<PathBuf>,
    pub loading: Option<PathBuf>,
    pub error: Option<PathBuf>,
    pub params: Vec<RouteParam>,
}

pub fn scan_app_dir(app_dir: impl AsRef<Path>) -> Result<Vec<Route>> {
    let app_dir = app_dir.as_ref();
    if !app_dir.is_dir() {
        return Err(RouterError::AppDirMissing(app_dir.to_path_buf()));
    }

    let mut routes = Vec::new();
    visit_dir(app_dir, app_dir, &mut routes)?;
    routes.sort_by(|left, right| left.path.cmp(&right.path).then(left.file.cmp(&right.file)));
    Ok(routes)
}

pub fn generate_route_types(routes: &[Route]) -> String {
    let route_union = if routes.is_empty() {
        "never".to_owned()
    } else {
        routes
            .iter()
            .map(|route| json_string(&route.path))
            .collect::<Vec<_>>()
            .join(" | ")
    };

    let mut out = String::new();
    out.push_str(GENERATED_ROUTE_TYPES_HEADER);
    out.push('\n');
    out.push_str("declare global {\n");
    out.push_str("  namespace Ferrite {\n");
    out.push_str("    export type RoutePath = ");
    out.push_str(&route_union);
    out.push_str(";\n\n");
    out.push_str("    export type RouteParams = {\n");

    for route in routes {
        out.push_str("      ");
        out.push_str(&json_string(&route.path));
        out.push_str(": ");
        out.push_str(&format_params(&route.params));
        out.push_str(";\n");
    }

    out.push_str("    };\n");
    out.push_str("  }\n");
    out.push_str("}\n");
    out.push_str("export {};\n");
    out
}

pub fn find_document_file(app_dir: impl AsRef<Path>) -> Option<PathBuf> {
    let app_dir = app_dir.as_ref();
    ["document.tsx", "document.ts", "document.jsx", "document.js"]
        .iter()
        .map(|name| app_dir.join(name))
        .find(|path| path.is_file())
}

fn visit_dir(app_dir: &Path, current: &Path, routes: &mut Vec<Route>) -> Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            visit_dir(app_dir, &path, routes)?;
        } else if is_page_file(&path) {
            routes.push(route_from_page_file(app_dir, &path)?);
        }
    }

    Ok(())
}

fn route_from_page_file(app_dir: &Path, file: &Path) -> Result<Route> {
    let route_dir = file.parent().unwrap_or(app_dir);
    let relative = route_dir.strip_prefix(app_dir).unwrap_or(route_dir);

    let mut path_parts = Vec::new();
    let mut params = Vec::new();

    for part in relative.components() {
        let raw_segment = part.as_os_str().to_string_lossy();
        if raw_segment.is_empty() {
            continue;
        }

        if let Some(segment) = parse_segment(&raw_segment)? {
            path_parts.push(segment.path_part);
            if let Some(param) = segment.param {
                params.push(param);
            }
        }
    }

    let path = if path_parts.is_empty() {
        "/".to_owned()
    } else {
        format!("/{}", path_parts.join("/"))
    };

    Ok(Route {
        path,
        file: file.to_path_buf(),
        layouts: layout_files_for_route(app_dir, route_dir),
        loading: nearest_convention_file_for_route(app_dir, route_dir, "loading"),
        error: nearest_convention_file_for_route(app_dir, route_dir, "error"),
        params,
    })
}

fn layout_files_for_route(app_dir: &Path, route_dir: &Path) -> Vec<PathBuf> {
    let relative = route_dir.strip_prefix(app_dir).unwrap_or(route_dir);
    let mut layouts = Vec::new();
    let mut current = app_dir.to_path_buf();

    if let Some(layout) = layout_file_in(&current) {
        layouts.push(layout);
    }

    for part in relative.components() {
        current.push(part.as_os_str());
        if let Some(layout) = layout_file_in(&current) {
            layouts.push(layout);
        }
    }

    layouts
}

fn layout_file_in(dir: &Path) -> Option<PathBuf> {
    ["layout.tsx", "layout.ts", "layout.jsx", "layout.js"]
        .iter()
        .map(|name| dir.join(name))
        .find(|path| path.is_file())
}

fn nearest_convention_file_for_route(
    app_dir: &Path,
    route_dir: &Path,
    stem: &str,
) -> Option<PathBuf> {
    let relative = route_dir.strip_prefix(app_dir).unwrap_or(route_dir);
    let mut current = app_dir.to_path_buf();
    let mut found = convention_file_in(&current, stem);

    for part in relative.components() {
        current.push(part.as_os_str());
        if let Some(file) = convention_file_in(&current, stem) {
            found = Some(file);
        }
    }

    found
}

fn convention_file_in(dir: &Path, stem: &str) -> Option<PathBuf> {
    ["tsx", "ts", "jsx", "js"]
        .iter()
        .map(|extension| dir.join(format!("{stem}.{extension}")))
        .find(|path| path.is_file())
}

fn is_page_file(path: &Path) -> bool {
    let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
        return false;
    };
    let Some(extension) = path.extension().and_then(|extension| extension.to_str()) else {
        return false;
    };

    stem == "page" && matches!(extension, "ts" | "tsx" | "js" | "jsx")
}

struct ParsedSegment {
    path_part: String,
    param: Option<RouteParam>,
}

fn parse_segment(segment: &str) -> Result<Option<ParsedSegment>> {
    if segment.starts_with('(') && segment.ends_with(')') {
        return Ok(None);
    }

    if segment.starts_with("[[...") && segment.ends_with("]]") {
        let name = &segment[5..segment.len() - 2];
        validate_param_name(segment, name)?;
        return Ok(Some(ParsedSegment {
            path_part: format!("*{name}?"),
            param: Some(RouteParam {
                name: name.to_owned(),
                kind: RouteParamKind::OptionalCatchAll,
            }),
        }));
    }

    if segment.starts_with("[...") && segment.ends_with(']') {
        let name = &segment[4..segment.len() - 1];
        validate_param_name(segment, name)?;
        return Ok(Some(ParsedSegment {
            path_part: format!("*{name}"),
            param: Some(RouteParam {
                name: name.to_owned(),
                kind: RouteParamKind::CatchAll,
            }),
        }));
    }

    if segment.starts_with('[') && segment.ends_with(']') {
        let name = &segment[1..segment.len() - 1];
        validate_param_name(segment, name)?;
        return Ok(Some(ParsedSegment {
            path_part: format!(":{name}"),
            param: Some(RouteParam {
                name: name.to_owned(),
                kind: RouteParamKind::Dynamic,
            }),
        }));
    }

    if segment.contains('[') || segment.contains(']') {
        return Err(RouterError::InvalidRouteSegment(segment.to_owned()));
    }

    Ok(Some(ParsedSegment {
        path_part: segment.to_owned(),
        param: None,
    }))
}

fn validate_param_name(segment: &str, name: &str) -> Result<()> {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err(RouterError::InvalidRouteSegment(segment.to_owned()));
    };

    if !(first.is_ascii_alphabetic() || first == '_') {
        return Err(RouterError::InvalidRouteSegment(segment.to_owned()));
    }

    if chars.all(|char| char.is_ascii_alphanumeric() || char == '_') {
        Ok(())
    } else {
        Err(RouterError::InvalidRouteSegment(segment.to_owned()))
    }
}

fn format_params(params: &[RouteParam]) -> String {
    if params.is_empty() {
        return "{}".to_owned();
    }

    let fields = params
        .iter()
        .map(|param| {
            let value_type = match param.kind {
                RouteParamKind::Dynamic => "string",
                RouteParamKind::CatchAll => "string[]",
                RouteParamKind::OptionalCatchAll => "string[] | undefined",
            };
            format!("{}: {value_type}", json_string(&param.name))
        })
        .collect::<Vec<_>>()
        .join("; ");

    format!("{{ {fields} }}")
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scans_static_dynamic_and_grouped_routes() {
        let temp = tempfile::tempdir().unwrap();
        let app = temp.path().join("app");
        fs::create_dir_all(app.join("(marketing)/posts/[id]")).unwrap();
        fs::create_dir_all(app.join("docs/[...slug]")).unwrap();
        fs::write(app.join("page.tsx"), "").unwrap();
        fs::write(app.join("layout.tsx"), "").unwrap();
        fs::write(app.join("loading.tsx"), "").unwrap();
        fs::write(app.join("error.tsx"), "").unwrap();
        fs::write(app.join("(marketing)/layout.tsx"), "").unwrap();
        fs::write(app.join("(marketing)/posts/error.tsx"), "").unwrap();
        fs::write(app.join("(marketing)/posts/[id]/loading.tsx"), "").unwrap();
        fs::write(app.join("(marketing)/posts/[id]/page.tsx"), "").unwrap();
        fs::write(app.join("docs/[...slug]/page.jsx"), "").unwrap();

        let routes = scan_app_dir(&app).unwrap();

        assert_eq!(
            routes
                .iter()
                .map(|route| route.path.as_str())
                .collect::<Vec<_>>(),
            vec!["/", "/docs/*slug", "/posts/:id"]
        );
        assert_eq!(
            routes[2].params,
            vec![RouteParam {
                name: "id".to_owned(),
                kind: RouteParamKind::Dynamic,
            }]
        );
        assert_eq!(
            routes[0]
                .loading
                .as_ref()
                .unwrap()
                .strip_prefix(&app)
                .unwrap(),
            Path::new("loading.tsx")
        );
        assert_eq!(
            routes[0]
                .error
                .as_ref()
                .unwrap()
                .strip_prefix(&app)
                .unwrap(),
            Path::new("error.tsx")
        );
        assert_eq!(
            routes[2]
                .loading
                .as_ref()
                .unwrap()
                .strip_prefix(&app)
                .unwrap(),
            Path::new("(marketing)/posts/[id]/loading.tsx")
        );
        assert_eq!(
            routes[2]
                .error
                .as_ref()
                .unwrap()
                .strip_prefix(&app)
                .unwrap(),
            Path::new("(marketing)/posts/error.tsx")
        );
        assert_eq!(
            routes[2]
                .layouts
                .iter()
                .map(|path| path.strip_prefix(&app).unwrap().display().to_string())
                .collect::<Vec<_>>(),
            vec!["layout.tsx", "(marketing)/layout.tsx"]
        );
    }

    #[test]
    fn rejects_missing_app_dir() {
        let temp = tempfile::tempdir().unwrap();
        let error = scan_app_dir(temp.path().join("app")).unwrap_err();
        assert!(matches!(error, RouterError::AppDirMissing(_)));
    }

    #[test]
    fn rejects_malformed_dynamic_segment() {
        let temp = tempfile::tempdir().unwrap();
        let app = temp.path().join("app");
        fs::create_dir_all(app.join("[bad-name]")).unwrap();
        fs::write(app.join("[bad-name]/page.tsx"), "").unwrap();

        let error = scan_app_dir(&app).unwrap_err();

        assert!(
            matches!(error, RouterError::InvalidRouteSegment(segment) if segment == "[bad-name]")
        );
    }

    #[test]
    fn finds_root_document_file() {
        let temp = tempfile::tempdir().unwrap();
        let app = temp.path().join("app");
        fs::create_dir_all(&app).unwrap();
        fs::write(app.join("document.tsx"), "").unwrap();

        let document = find_document_file(&app).unwrap();

        assert_eq!(document, app.join("document.tsx"));
    }

    #[test]
    fn generates_route_types() {
        let routes = vec![
            Route {
                path: "/".to_owned(),
                file: PathBuf::from("app/page.tsx"),
                layouts: vec![PathBuf::from("app/layout.tsx")],
                loading: None,
                error: None,
                params: vec![],
            },
            Route {
                path: "/posts/:id".to_owned(),
                file: PathBuf::from("app/posts/[id]/page.tsx"),
                layouts: vec![PathBuf::from("app/layout.tsx")],
                loading: None,
                error: None,
                params: vec![RouteParam {
                    name: "id".to_owned(),
                    kind: RouteParamKind::Dynamic,
                }],
            },
            Route {
                path: "/docs/*slug?".to_owned(),
                file: PathBuf::from("app/docs/[[...slug]]/page.tsx"),
                layouts: vec![PathBuf::from("app/layout.tsx")],
                loading: None,
                error: None,
                params: vec![RouteParam {
                    name: "slug".to_owned(),
                    kind: RouteParamKind::OptionalCatchAll,
                }],
            },
        ];

        let types = generate_route_types(&routes);

        assert!(
            types.contains("export type RoutePath = \"/\" | \"/posts/:id\" | \"/docs/*slug?\";")
        );
        assert!(types.contains("\"/posts/:id\": { \"id\": string };"));
        assert!(types.contains("\"/docs/*slug?\": { \"slug\": string[] | undefined };"));
    }
}
